services:

  rabbitmq:
    image: rabbitmq:3
    container_name: tradepro-mq
    ports:
      - '5672:5672'
    networks:
      - local

  postgres:
    image: postgres:14.5
    restart: always
    container_name: tradepro-db
    volumes:
      - tradedb-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: trade@123
      POSTGRES_DB: postgres
    ports:
      - 36000:5432
    networks:  
      - local

  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_NAME: postgres
      #DB_HOST: host.docker.internal
      DB_HOST: tradepro-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: trade@123 
      MESSAGE_URL: amqp://tradepro-mq:5672
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - 3001:3000
    networks:
      - local

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - 8000:80
    networks:
      - local
      
networks:
  local:

volumes:
    tradedb-vol:
        external: true